# Generated by Django 2.0 on 2018-09-10 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_category_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post',
            field=models.TextField(blank=True),
        ),
    ]
