# Generated by Django 2.0 on 2018-09-10 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_post_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='captions',
            field=models.TextField(blank=True),
        ),
    ]
