# Generated by Django 2.0 on 2018-09-10 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_post_captions'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='quote',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='post',
            name='quote_by',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
