# Generated by Django 2.0 on 2018-09-10 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_auto_20180910_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='captions_para_2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='post',
            name='captions_para_3',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='post',
            name='post_para_2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='post',
            name='post_para_3',
            field=models.TextField(blank=True),
        ),
    ]
