# Generated by Django 2.0 on 2018-09-13 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_post_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to='post_image/%Y/%m/%d/'),
        ),
    ]
